curl --location 'http://127.0.0.1:3008//dendogram/generate?affinity=bert-embedding-cosine' \
--header 'Content-Type: application/json' \
--data-raw '{
    "app_name": "org.telegram.messenger",
    "features": [
    "good app",
    "nice app",
    "love app",
    "great app",
    "use app",
    "good browser",
    "very good app",
    "like app",
    "work",
    "send message",
    "good",
    "have problem",
    "love",
    "thank",
    "bad app",
    "excellent app",
    "very nice app",
    "great browser",
    "create account",
    "have issue",
    "download app",
    "give star",
    "open app",
    "awesome",
    "good experience",
    "op",
    "awesome app",
    "make call",
    "update app",
    "app",
    "amazing app",
    "good application",
    "message app",
    "good service",
    "make account",
    "great experience",
    "use google voice",
    "get notification",
    "nice",
    "receive message",
    "good job",
    "have app",
    "problem",
    "send email",
    "excellent browser",
    "gud",
    "super app",
    "star",
    "excellent service",
    "wonderful app",
    "install app",
    "lot",
    "trash",
    "cool app",
    "good work",
    "love browser",
    "use browser",
    "ad",
    "great",
    "osm",
    "block ad",
    "excellent",
    "have lot",
    "use discord",
    "fun",
    "very good browser",
    "call friend",
    "great way",
    "open email",
    "super",
    "good luck",
    "good quality",
    "use firefox",
    "great service",
    "have trouble",
    "whatsapp",
    "google",
    "nice application",
    "send text",
    "issue",
    "enjoy app",
    "nice browser",
    "receive call",
    "receive verification code",
    "suck",
    "get app",
    "get message",
    "nc",
    "bad experience",
    "nice aap",
    "use",
    "update",
    "crash",
    "use skype",
    "viber",
    "waste",
    "call app",
    "get verification code",
    "keep good work",
    "mast",
    "very nice",
    "way",
    "add option",
    "fix bug",
    "play game",
    "garbage",
    "receive notification",
    "superb",
    "excelent",
    "send verification code",
    "send video",
    "too many ad",
    "very bad app",
    "delete app",
    "delete message",
    "gd",
    "save contact",
    "send picture",
    "useless app",
    "fix problem",
    "idk",
    "noice",
    "send photo",
    "very useful app",
    "chat app",
    "drop call",
    "forget password",
    "hate app",
    "have idea",
    "love discord",
    "send code",
    "supar",
    "use edge",
    "verify update",
    "absolute bias",
    "fantastic app",
    "good web browser",
    "goood",
    "have bug",
    "keep",
    "sai aung murng",
    "very good experience",
    "send mail",
    "add friend",
    "gg",
    "good way",
    "instal app",
    "love google voice",
    "need help",
    "nyc",
    "open account",
    "save datum",
    "terrible app",
    "bug",
    "face problem",
    "give option",
    "have option",
    "love firefox",
    "ok",
    "stupid app",
    "very good service",
    "add feature",
    "awesome browser",
    "create new account",
    "have phone",
    "nc app",
    "perfect",
    "perfect app",
    "send verification message",
    "use yahoo mail",
    "amazing",
    "favorite browser",
    "goog",
    "great application",
    "rate star",
    "receive code",
    "receive email",
    "receive text",
    "edit",
    "year",
    "change password",
    "fix app",
    "great job",
    "have friend",
    "need improvement",
    "open messenger",
    "rate app",
    "use line",
    "use application",
    "violate term",
    "watch video",
    "download",
    "a",
    "browse app",
    "excelente",
    "get code",
    "good aap",
    "make phone call",
    "see message",
    "use brave",
    "use chrome",
    "waste time",
    "download video",
    "experience",
    "block account",
    "call people",
    "cool",
    "delete",
    "delete contact",
    "excellent experience",
    "get new phone",
    "give",
    "give notification",
    "good apk",
    "good messenger",
    "good morning",
    "have account",
    "like browser",
    "need app",
    "nice work",
    "recommend app",
    "send link",
    "solve problem",
    "use yahoo",
    "useful app",
    "verygood",
    "delete email",
    "dope",
    "give five star",
    "good performance",
    "good thing",
    "horrible app",
    "make new account",
    "s",
    "send sm",
    "try app",
    "make app",
    "t",
    "best",
    "exellent",
    "face issue",
    "first time",
    "good working",
    "have number",
    "login account",
    "need",
    "need update",
    "really good app",
    "send notification",
    "send text message",
    "take time",
    "text friend",
    "use opera",
    "use signal",
    "very nice application",
    "have good experience",
    "ban account",
    "delete account",
    "download file",
    "excellence",
    "find way",
    "get call",
    "get update",
    "have great experience",
    "love yahoo",
    "new update",
    "send msg",
    "send sms",
    "take lot",
    "use number",
    "use viber",
    "xxx",
    "contact",
    "change number",
    "deserve star",
    "drain battery",
    "excellent thank",
    "fantastic",
    "find app",
    "give problem",
    "good ap",
    "great alternative",
    "nice experience",
    "nyc app",
    "okey",
    "recover account",
    "send verification",
    "use whatsapp",
    "very good",
    "very good application",
    "very good quality",
    "get email",
    "g",
    "v",
    "complaint",
    "garbage app",
    "get account",
    "get number",
    "give number",
    "good apps",
    "good stuff",
    "goof",
    "have access",
    "like",
    "love edge",
    "love gmail",
    "message",
    "message friend",
    "number",
    "open link",
    "play video",
    "send image",
    "very bad experience",
    "video call",
    "bad update",
    "reinstall app",
    "e",
    "o",
    "p",
    "amazing browser",
    "beautiful app",
    "change phone",
    "change review",
    "excellent application",
    "exelent",
    "fantastic browser",
    "fast browser",
    "get error",
    "good mobile browser",
    "good platform",
    "have fun",
    "junk",
    "king",
    "line",
    "love game",
    "love it",
    "love privacy",
    "love yahoo mail",
    "m",
    "n",
    "need lot",
    "open chat",
    "open new tab",
    "option",
    "switch account",
    "take money",
    "text people",
    "too much ad",
    "use email",
    "use opera mini",
    "use phone number",
    "use voice",
    "verify account",
    "watch youtube",
    "cancel subscription",
    "b",
    "awesome experience",
    "change color",
    "deliver message",
    "exllent",
    "favourite browser",
    "find friend",
    "fix issue",
    "get text",
    "give one star",
    "go",
    "good message app",
    "great option",
    "great quality",
    "have",
    "have experience",
    "have facebook",
    "have way",
    "love application",
    "love signal",
    "lovely app",
    "make video call",
    "meh",
    "miss call",
    "notification",
    "send pic",
    "set account",
    "superb app",
    "texte app",
    "too many bug",
    "too much spam",
    "trash app",
    "use phone",
    "use service",
    "user",
    "v good",
    "very nice browser",
    "video",
    "waste app",
    "wonderful",
    "j",
    "time",
    "access account",
    "bad application",
    "comment",
    "discord",
    "favorite app",
    "firefox",
    "good alternative",
    "good communication",
    "good good",
    "great messaging app",
    "great work",
    "have error",
    "lag",
    "like application",
    "like new update",
    "lose number",
    "make friend",
    "md",
    "need work",
    "omg",
    "receive text message",
    "register account",
    "reset password",
    "restart phone",
    "save page",
    "save new contact",
    "save video",
    "send massage",
    "tnx",
    "use gv",
    "use lot",
    "valo",
    "very good aap",
    "want app",
    "wonderful experience",
    "yas",
    "browser",
    "q",
    "y",
    "aa",
    "add contact",
    "awesome application",
    "bangladesh",
    "brilliant app",
    "buy nitro",
    "close app",
    "ease",
    "email",
    "f",
    "find contact",
    "forgot password",
    "get access",
    "get contact",
    "get new number",
    "good game",
    "good search engine",
    "good whatsapp",
    "gud app",
    "hate new update",
    "have ad",
    "have hard time",
    "have time",
    "help",
    "kk",
    "like fact",
    "like viber",
    "like way",
    "lose account",
    "lose phone",
    "love line",
    "love messenger",
    "love opera",
    "love viber",
    "mm",
    "nic app",
    "nice good",
    "nice service",
    "nice update",
    "open mail",
    "opera mini",
    "perfect browser",
    "read message",
    "show ad",
    "show error",
    "solve issue",
    "soo good",
    "take long time",
    "take picture",
    "thank god",
    "uninstall app",
    "uninstalle app",
    "update whatsapp",
    "use telegram",
    "usefull app",
    "verify number",
    "very useful application",
    "watch movie",
    "waw",
    "woow",
    "wow",
    "yay",
    "jan",
    "add phone number",
    "amazing experience",
    "bed",
    "best app",
    "block app",
    "bravo",
    "break app",
    "check email",
    "contact friend",
    "d",
    "describe experience",
    "enjoy browser",
    "error",
    "ex",
    "five star",
    "freeze",
    "get chance",
    "give code",
    "glitchy",
    "good communication app",
    "good place",
    "gooood",
    "great love",
    "great tool",
    "have phone number",
    "hh",
    "horrible experience",
    "join group",
    "l",
    "like messenger",
    "load page",
    "lose connection",
    "love snapchat",
    "make new friend",
    "make sense",
    "need option",
    "nic",
    "nice job",
    "okk",
    "oo",
    "otp",
    "overall good",
    "poor app",
    "really good browser",
    "receive mail",
    "reset phone",
    "save number",
    "search contact",
    "send file",
    "service",
    "sign",
    "so nice app",
    "stop ad",
    "super application",
    "suspend account",
    "update problem",
    "update review",
    "upgrade app",
    "upload video",
    "use facebook",
    "use gmail",
    "use snapchat",
    "use text",
    "verify phone number",
    "vgood",
    "x",
    "zero star",
    "mom",
    "r",
    "rate",
    "u",
    "access app",
    "access whatsapp",
    "add extension",
    "add number",
    "alot",
    "awesomeness",
    "bad service",
    "bloatware",
    "broken",
    "bulok",
    "chat",
    "chat friend",
    "check app",
    "decent app",
    "do job",
    "do update",
    "download image",
    "download movie",
    "drop sms support",
    "excellent work",
    "exilent",
    "exlent",
    "fast app",
    "fix",
    "freeze phone",
    "gd app",
    "get star",
    "get lot",
    "get mail",
    "get otp",
    "get sim card",
    "get thing",
    "give three star",
    "good browsing experience",
    "good day",
    "good email app",
    "good mail",
    "good option",
    "good social app",
    "good thank",
    "gooooood",
    "great platform",
    "great thank",
    "great web browser",
    "h",
    "hand",
    "hate ad",
    "have sim card",
    "have contact",
    "have facebook account",
    "have feature",
    "have glitch",
    "have message",
    "have money",
    "have question",
    "have word",
    "help alot",
    "helpful app",
    "join open chat",
    "k",
    "legit",
    "life",
    "life saver",
    "like edge",
    "like signal",
    "like yahoo mail",
    "load app",
    "load message",
    "lock account",
    "login problem",
    "lose contact",
    "love messenger kid",
    "love new update",
    "love opera mini",
    "love skype",
    "love text",
    "love way",
    "love whatsapp",
    "make change",
    "make money",
    "make payment",
    "malware",
    "mantap",
    "mast app",
    "mast hai",
    "muy buena",
    "nice apk",
    "nich",
    "niec",
    "okay",
    "one star",
    "ooo",
    "open message",
    "opera",
    "poor service",
    "pop ad",
    "receive picture",
    "ruin app",
    "save time",
    "scan qr code",
    "see ad",
    "see app",
    "see picture",
    "see text",
    "show contact name",
    "show message",
    "show notification",
    "show number",
    "sign new account",
    "so good app",
    "so much fun",
    "soo",
    "support",
    "sync email",
    "take age",
    "take number",
    "take too much time",
    "thank u",
    "tt",
    "update chrome",
    "use google",
    "use messenger",
    "use vpn",
    "use wechat",
    "uu",
    "verry good app",
    "very cool app",
    "very great app",
    "word",
    "work app",
    "wrost app",
    "change font",
    "make option",
    "get new message notification",
    "favorite",
    "w",
    "dr",
    "access email",
    "add",
    "add people",
    "aman",
    "answer call",
    "aung",
    "awesome thank",
    "bad connection",
    "bad messenger",
    "bagus",
    "block",
    "block number",
    "browse internet",
    "buggy",
    "change icon",
    "change phone number",
    "change rating",
    "change setting",
    "clear datum",
    "clear picture",
    "congratulation",
    "create problem",
    "create profile",
    "delete number",
    "delete conversation",
    "disable account",
    "do stuff",
    "do thing",
    "do video call",
    "easy way",
    "edit contact",
    "end encryption",
    "excellent performance",
    "excellent way",
    "exelente",
    "fine",
    "fine app",
    "friend",
    "get bug",
    "get email notification",
    "get error message",
    "get help",
    "give access",
    "give zero star",
    "god",
    "goid",
    "good chat",
    "good connection",
    "good email",
    "good internet browser",
    "good messenger app",
    "good site",
    "good social medium",
    "good video",
    "goodapp",
    "grate app",
    "great place",
    "great thing",
    "grow account",
    "hack account",
    "have email",
    "have line",
    "have clue",
    "have skype",
    "have yahoo mail",
    "hear person",
    "hear voice",
    "iam",
    "idea",
    "kill app",
    "know password",
    "like update",
    "love chrome",
    "love experience",
    "love filter",
    "loveit",
    "many bug",
    "need ability",
    "need more improvement",
    "need more update",
    "never problem",
    "nice working",
    "not good app",
    "okay good app",
    "one",
    "one word",
    "open browser",
    "open whatsapp",
    "overall good app",
    "perfecto",
    "piece",
    "place call",
    "play youtube",
    "poor connection",
    "pretty good app",
    "protect privacy",
    "put number",
    "read email",
    "read review",
    "really nice app",
    "receive incoming call",
    "receive otp",
    "receive sms",
    "recover password",
    "register number",
    "remove ability",
    "remove ad",
    "remove sms support",
    "resolve issue",
    "rubbish app",
    "save contact number",
    "say error",
    "se",
    "see contact",
    "send attachment",
    "send chat",
    "send gifs",
    "send medium",
    "show contact",
    "sign account",
    "simply good browser",
    "so fun",
    "so good",
    "solid app",
    "spam",
    "spy app",
    "stop app",
    "super browser",
    "super duper",
    "sync contact",
    "sync mail",
    "take more time",
    "take phone",
    "take screenshot",
    "take while",
    "terrible experience",
    "texte friend",
    "thankyou",
    "top",
    "update phone",
    "update whatsapp business",
    "use account",
    "use brave browser",
    "use mobile",
    "v good app",
    "version",
    "very bad",
    "very fast browser",
    "very good condition",
    "very gud",
    "very important app",
    "vg",
    "w app",
    "watch ad",
    "woww",
    "write email",
    "write review",
    "ww",
    "bring update",
    "change username",
    "take day",
    "have sound",
    "good android browser",
    "enjoy",
    "ki",
    "aap",
    "gmail",
    "abheka",
    "access contact",
    "acha",
    "add more filter",
    "add new contact",
    "add vpn",
    "ahmadahmad",
    "amazing application",
    "app crash",
    "ask friend",
    "awful app",
    "awsome",
    "aww",
    "badass",
    "bad",
    "bag",
    "bahut",
    "best browser",
    "block all ad",
    "boom",
    "boss",
    "bruno",
    "buy new phone",
    "buy number",
    "c",
    "call family",
    "cause problem",
    "change name",
    "change profile picture",
    "change status",
    "check message",
    "clear cache",
    "clear voice",
    "click link",
    "close account",
    "close tab",
    "code",
    "communicate app",
    "communicate friend",
    "compose email",
    "connection",
    "cool beans",
    "copy contact",
    "create app",
    "day",
    "de",
    "delay",
    "develop app",
    "do app",
    "do call",
    "download line",
    "download music",
    "download photo",
    "download picture",
    "download problem",
    "download speed",
    "download thing",
    "do",
    "end call",
    "enjoy experience",
    "enjoy service",
    "enter number",
    "excellent alternative",
    "excellent communication",
    "exceptional app",
    "experience bug",
    "experience high volume",
    "experience issue",
    "extension",
    "fabulous app",
    "fabulous",
    "face lot",
    "face time",
    "fast browsing",
    "ff",
    "finally",
    "find option",
    "freedom",
    "game",
    "get ad",
    "get friend",
    "get new update",
    "get phone",
    "give error",
    "give phone number",
    "give update",
    "good browse app",
    "good phone app",
    "good project",
    "good update",
    "good use",
    "good vibe",
    "good video quality",
    "goog app",
    "goood app",
    "goooood",
    "great call",
    "great connection",
    "great feature",
    "great game",
    "great messenger app",
    "great reception",
    "great search engine",
    "group tab",
    "happy new year",
    "have ad blocker",
    "have bad experience",
    "have complaint",
    "have function",
    "have good time",
    "have google voice",
    "have iphone",
    "have need",
    "have one problem",
    "have privacy",
    "have right",
    "have same google voice number",
    "have same number",
    "have same problem",
    "have second number",
    "have service",
    "have wifi",
    "hell",
    "hhh",
    "home",
    "i",
    "ilikeit",
    "jjj",
    "job",
    "keep contact",
    "keep family",
    "keep opening",
    "keep touch",
    "leave review",
    "life saving",
    "like ad",
    "like brave browser",
    "like game",
    "like google voice",
    "like idea",
    "like messenger kid",
    "like privacy",
    "likhon",
    "load",
    "load email",
    "lock",
    "look",
    "lose ability",
    "lose datum",
    "lose password",
    "lose phone number",
    "love brave",
    "love fact",
    "love feature",
    "love google",
    "love kid messenger",
    "love layout",
    "love service",
    "love this app",
    "love update",
    "lovely",
    "merge contact",
    "mst",
    "need permission",
    "need code",
    "need phone number",
    "nice ap",
    "nice apps",
    "nice option",
    "nice whatsapp",
    "nicr",
    "nine app",
    "not good",
    "ok thank",
    "only thing",
    "only way",
    "open contact",
    "open line",
    "open new account",
    "open viber",
    "owesome",
    "pain",
    "pathetic app",
    "phone",
    "poor customer service",
    "poor performance",
    "pp",
    "prefer firefox",
    "put email",
    "put phone number",
    "quality",
    "rdxabhi",
    "read text",
    "realy",
    "recieve call",
    "register phone number",
    "reliable app",
    "remove ai",
    "remove channel",
    "reply message",
    "review app",
    "run app",
    "sathyamukthi",
    "save photo",
    "scam",
    "search",
    "see friend",
    "see notification",
    "see people",
    "see photo",
    "see update",
    "sell datum",
    "send gif",
    "send lot",
    "send mms",
    "send money",
    "send snap",
    "send verification text",
    "share photo",
    "share screen",
    "share video",
    "show app",
    "show name",
    "show time",
    "sign process",
    "simple",
    "smart",
    "smooth",
    "snap chat",
    "so far so good",
    "so many bug",
    "sooo",
    "sound",
    "suck number",
    "suggestion",
    "take gb",
    "take a few minute",
    "take so much time",
    "talk friend",
    "tank",
    "tell friend",
    "terbaik",
    "text mom",
    "thx",
    "trouble",
    "trust google",
    "try lot",
    "update account",
    "update browser",
    "update contact",
    "update late version",
    "update line",
    "update messenger",
    "update new version",
    "upload file",
    "upload picture",
    "use all time",
    "use filter",
    "use message",
    "use microsoft edge",
    "use open chat feature",
    "use password",
    "veri",
    "very bad update",
    "very good apk",
    "very nice aap",
    "very nice and useful app",
    "very user",
    "very very good app",
    "want option",
    "watch youtube video",
    "well app",
    "well browse app",
    "whatapp",
    "work good",
    "wow nice app",
    "yahoo",
    "yep",
    "z",
    "dec",
    "lose chunk",
    "add thing",
    "change ui",
    "have stuff",
    "get all email",
    "bad dark mode",
    "disturb mode",
    "top developer",
    "upload photo",
    "start",
    "yer",
    "call",
    "zz",
    "place",
    "ml",
    "ability",
    "absolutely garbage",
    "absolutely great app",
    "access setting",
    "account",
    "achha hai",
    "activate account",
    "add ability",
    "add ad",
    "add blocker",
    "add child",
    "add credit",
    "add delete",
    "add delete option",
    "add money",
    "add more feature",
    "add on",
    "add story",
    "address bar",
    "ads",
    "aj",
    "aka bloody blood",
    "akber",
    "alright",
    "ameze app",
    "app good",
    "appreciate app",
    "attach photo",
    "awesom",
    "awesome service",
    "awful",
    "backup chat",
    "bad browser",
    "bahut sundar",
    "baik",
    "ban",
    "bast app",
    "bekar",
    "bit",
    "block acc",
    "buena",
    "business",
    "buy sim card",
    "call cousin",
    "call text",
    "change account",
    "change email address",
    "change profile",
    "change theme",
    "computer",
    "connect family",
    "consume lot",
    "contact people",
    "coo",
    "cool browser",
    "cool thank",
    "copy image",
    "crash lot",
    "crash phone",
    "creat account",
    "create new tab",
    "customer support",
    "datum",
    "decent browser",
    "default browser",
    "delet post",
    "delete post",
    "demand",
    "design app",
    "dial number",
    "difficulty",
    "disgusting app",
    "do business",
    "do good job",
    "do great job",
    "do lot",
    "do right thing",
    "do search",
    "do trick",
    "do work",
    "download messenger",
    "download option",
    "dumb app",
    "easy app",
    "easy use",
    "edit message",
    "ek",
    "end",
    "enter app",
    "enter password",
    "excellent quality",
    "excellente",
    "exceptional browser",
    "excilent",
    "exilant",
    "exit app",
    "export contact",
    "facebook",
    "fav app",
    "favourite app",
    "feedback",
    "fi",
    "fin",
    "find account",
    "find bug",
    "find information",
    "find number",
    "find thing",
    "fix discord",
    "fix glitch",
    "force",
    "force user",
    "free fire",
    "ganda",
    "genius",
    "get",
    "get alot",
    "get confirmation code",
    "get crash",
    "get dark mode",
    "get hold",
    "get information",
    "get job",
    "get message notification",
    "get messenger",
    "get money",
    "get old account",
    "get option",
    "get problem",
    "get reply",
    "get sm",
    "get verification",
    "get video",
    "give five star rating",
    "give four star",
    "give more star",
    "glitch",
    "godd app",
    "good line",
    "good and safe app",
    "good browser app",
    "good browsing",
    "good deal",
    "good friend",
    "good nice app",
    "good night",
    "good one",
    "good quality app",
    "good quality video calling",
    "good reception",
    "good result",
    "good software",
    "good sound",
    "good support",
    "good time",
    "good ui",
    "good version",
    "good video call",
    "good website",
    "good wifi",
    "goodness",
    "google chrome",
    "gooo",
    "goot",
    "got app",
    "grear app",
    "great aap",
    "great and secure app",
    "great app love",
    "great audio",
    "great communication app",
    "great performance",
    "great site",
    "great stuff",
    "great ui",
    "great video",
    "great video quality",
    "gut",
    "hang",
    "hate update",
    "have chance",
    "have channel",
    "have ability",
    "have android",
    "have big problem",
    "have browser",
    "have choice",
    "have control",
    "have dark mode",
    "have datum",
    "have difficulty",
    "have free vpn",
    "have gmail",
    "have good app",
    "have good internet connection",
    "have good security",
    "have google voice number",
    "have many filter",
    "have many problem",
    "have minute",
    "have password",
    "have phone service",
    "have quick access",
    "have reason",
    "have same issue",
    "have signal",
    "have suggestion",
    "have textnow",
    "have ton",
    "have too many problem",
    "have video",
    "have virus",
    "have yahoo account",
    "hear friend",
    "hear other person",
    "hear people",
    "help app",
    "help lot",
    "help when need question",
    "horrible",
    "horrible customer service",
    "horrible update",
    "hurt eye",
    "import bookmark",
    "improve app",
    "improve lot",
    "install",
    "install application",
    "install extension",
    "install line",
    "install messenger",
    "install telegram",
    "jj",
    "jk",
    "join telegram",
    "joss app",
    "just good browser",
    "justin shakil",
    "keep file",
    "keep number",
    "know problem",
    "know",
    "lack",
    "lagging",
    "late update",
    "launch app",
    "leave app",
    "leave home",
    "leee",
    "lightweight",
    "like app alot",
    "like brave",
    "like change",
    "like contact",
    "like discord",
    "like feature",
    "like line",
    "like opera",
    "like option",
    "like service",
    "like skype",
    "link number",
    "log account",
    "login",
    "login gmail account",
    "lose access",
    "lose all contact",
    "love ad",
    "love dis app",
    "love duo",
    "love life",
    "love messenger kids",
    "love microsoft edge",
    "love phone",
    "love security",
    "love site",
    "love textnow",
    "luv",
    "make review",
    "make server",
    "make switch",
    "make use",
    "master",
    "medium",
    "meet friend",
    "meet new one",
    "messenger",
    "mim",
    "mind",
    "miss lot",
    "mk",
    "moe chit thu",
    "morning",
    "most beautiful app",
    "most stupid app",
    "muhammad yousuf",
    "music",
    "muy buena app",
    "nah",
    "name",
    "need account",
    "need friend",
    "need more feature",
    "need more time",
    "need phone",
    "need second line",
    "need way",
    "nice alternative",
    "nice gmail",
    "nice l",
    "nice one",
    "nice pic",
    "nice thank",
    "nice way",
    "niceee",
    "night",
    "nil",
    "not bad app",
    "not bad",
    "not fan",
    "not user",
    "ok app",
    "ok browser",
    "okok",
    "om",
    "only app",
    "open application",
    "open camera",
    "open gmail",
    "open page",
    "open picture",
    "open source",
    "out standing",
    "pakistan",
    "pass information",
    "pawankumar",
    "pay bill",
    "pay phone bill",
    "perfection",
    "phenomenal experience",
    "play roblox",
    "plea",
    "pog",
    "port number",
    "post video",
    "power",
    "primary browser",
    "privacy",
    "privacy issue",
    "protect app",
    "provide good service",
    "provide option",
    "purchase sticker",
    "put star",
    "qa",
    "quit",
    "quite good",
    "read mail",
    "really fun",
    "really great app",
    "really nice browser",
    "reboot phone",
    "receive phone call",
    "receive sim card",
    "receive sm",
    "recent update",
    "recieve verification code",
    "recommend browser",
    "record call",
    "recovery account",
    "register app",
    "remove app",
    "remove smart reply",
    "reply",
    "reply email",
    "respect privacy",
    "ring phone",
    "rohit",
    "ru",
    "rubbish",
    "run",
    "run business",
    "save lot",
    "save password",
    "say account creation failure",
    "scan code",
    "secure app",
    "see difference",
    "see email",
    "see improvement",
    "see location",
    "see name",
    "see person",
    "see support",
    "see video",
    "send document",
    "send multiple photo",
    "send page",
    "send reply",
    "send time",
    "server access failure",
    "sex",
    "shame",
    "show video",
    "sign app",
    "sign problem",
    "signal",
    "skype",
    "slow app",
    "speed",
    "spend money",
    "sr",
    "start app",
    "steal datum",
    "such good app",
    "suck app",
    "sunil",
    "super experience",
    "super fast browser",
    "supet",
    "supper",
    "supper app",
    "take minute",
    "take second",
    "take care",
    "take hour",
    "talk family",
    "teacher",
    "text all friend",
    "text family",
    "text message",
    "thanku",
    "thik",
    "too many advertisement",
    "too much lag",
    "top app",
    "top notch",
    "transfer account",
    "uff",
    "unblock account",
    "update contact info",
    "update application",
    "update status",
    "use year",
    "use bluetooth",
    "use bluetooth headphone",
    "use chat",
    "use datum",
    "use g",
    "use google chrome",
    "use internet",
    "use it",
    "use opera browser",
    "use pay",
    "use people",
    "use platform",
    "use problem",
    "use samsung browser",
    "use textnow",
    "use thank",
    "use ton",
    "use video call",
    "use whatsapp business",
    "useful to good",
    "usefull",
    "valo app",
    "verify identity",
    "verify email",
    "very awesome app",
    "very bad application",
    "very bed",
    "very excellent app",
    "very good work",
    "very help",
    "very helpful app",
    "very nice experience",
    "very nice service",
    "very nyc",
    "very poor app",
    "very poor service",
    "very reliable app",
    "very secure app",
    "very slow app",
    "very use",
    "very useless app",
    "very very bad app",
    "very very nice app",
    "view message",
    "view picture",
    "violate rule",
    "voice",
    "vpn",
    "want phone number",
    "want contact",
    "want privacy",
    "waste datum",
    "waste lot",
    "well ever app",
    "well experience",
    "well video quality",
    "work fine",
    "work problem",
    "work video",
    "worst",
    "youtube",
    "youtube ad",
    "yyy",
    "zero",
    "improve platform",
    "very good not much error",
    "always reliable browser",
    "update o s firefox",
    "bring timeline voom",
    "bring logout option",
    "save snap",
    "see server member",
    "delete ad",
    "do many thing",
    "give proper download manager",
    "add indonesian language",
    "change dam ui design",
    "fantastic and amarzing whatsapp",
    "very goad whatsapp",
    "have stable connection",
    "bring app",
    "remixe image",
    "time favourite app",
    "have all same feature",
    "kembalikan fitur open chat",
    "fitur open chat",
    "add such ugly layout",
    "delay letter",
    "add more tablet specific optimization",
    "see profile picture",
    "nice sexy app",
    "find mom",
    "reinstall all bookmark",
    "have ad block",
    "get group message",
    "rip ai tester group",
    "say same thing",
    "top left",
    "show several control",
    "fill entire space",
    "support call",
    "give device",
    "top develope",
    "very good gmail app",
    "nj",
    "year experience",
    "class",
    "stars",
    "rf",
    "cc",
    "mb",
    "hu",
    "xd",
    "aaa",
    "aamir anshri",
    "absolute garbage",
    "absolute good thing",
    "absolute rubbish",
    "absolutely perfect app",
    "absolutely waste",
    "abul",
    "acc",
    "accept call",
    "accept google voice number",
    "accept phone number",
    "access information",
    "access line",
    "acha hai",
    "activate app",
    "activate sim card",
    "activate viber",
    "add star",
    "add account",
    "add app",
    "add attachment",
    "add brave",
    "add dark mode",
    "add daughter",
    "add effect",
    "add email",
    "add extension support",
    "add family member",
    "add freind",
    "add google account",
    "add lot",
    "add mark",
    "add more wallet",
    "add music",
    "add picture",
    "add profile picture",
    "add save",
    "add status",
    "add support",
    "add tab",
    "ahmadelikhidr",
    "album",
    "alhamdullilah",
    "aliraza",
    "allah",
    "allow ad",
    "allow login",
    "always bug",
    "always good service",
    "amazing app love",
    "amazing feature",
    "amazing quality",
    "amazing service",
    "amazing video quality",
    "amazing way",
    "aminul",
    "android phone",
    "android version",
    "anil",
    "answer phone call",
    "app rock",
    "app tamjid",
    "application",
    "archive community group",
    "ask google",
    "ask mom",
    "ask permission",
    "ask question",
    "aswom",
    "atif",
    "attach file",
    "attach phone number",
    "autofill name",
    "avarage",
    "avoid ad",
    "awesome filter",
    "awesome product",
    "awesome search engine",
    "awesome text",
    "awsam",
    "awsm",
    "ayan",
    "ayush",
    "az",
    "baaaaaad",
    "bablu",
    "bablu kumar",
    "back contact",
    "bad call",
    "bad customer service",
    "bad network",
    "bad quality",
    "bad review",
    "bakwa app",
    "bakwa hai",
    "ban app",
    "be multi device support",
    "beast",
    "beat app",
    "beats chrome",
    "beautiful",
    "berry good",
    "besst",
    "best application",
    "best web browser",
    "bestt",
    "beta",
    "bhangar",
    "bien",
    "bingo",
    "bless opera mini",
    "blessing",
    "block add",
    "block annoying ad",
    "block autoplay video",
    "block contact",
    "block email",
    "block lot",
    "block phone number",
    "blow mind",
    "bolo",
    "bom",
    "boooo",
    "brave",
    "bride",
    "bring chat head",
    "bring feature",
    "bring login",
    "bring old font",
    "bring old status",
    "bring option",
    "bring sms",
    "bro",
    "browse web",
    "bst",
    "bug problem",
    "bug report",
    "buggy app",
    "buy minute",
    "buy phone",
    "buy skype credit",
    "bwisit",
    "call all friend",
    "call bestie",
    "call drop",
    "call freind",
    "call girlfriend",
    "call other person",
    "call text people",
    "can",
    "cant log",
    "cant see",
    "care",
    "cause battery drain",
    "cause lot",
    "ccp spyware",
    "chance",
    "change",
    "change app",
    "change bitmoji",
    "change cell phone",
    "change channel",
    "change device",
    "change email",
    "change feature",
    "change language",
    "change logo",
    "change mobile",
    "change notification sound",
    "change size",
    "change text color",
    "change user",
    "chat a",
    "chat account",
    "chat head",
    "chat message",
    "chat tool",
    "chego",
    "chinese spyware",
    "choose app",
    "chrome browser",
    "classic",
    "clean phone",
    "clear",
    "clear call",
    "clear call history",
    "clear video",
    "collect datum",
    "commit suicide",
    "communication",
    "connect app",
    "connect call",
    "connect channel",
    "connect video call",
    "consume",
    "consume app",
    "consume too much space",
    "contact family",
    "contact parent",
    "content",
    "convenience",
    "cool bro",
    "cool experience",
    "coool",
    "coooool",
    "cp",
    "crash everytime",
    "crash time",
    "create acc",
    "create acount",
    "create application",
    "create gmail",
    "create group",
    "create new acc",
    "create new contact",
    "create new gmail account",
    "create new google account",
    "create page",
    "create password",
    "customize contact",
    "customize profile",
    "cute app",
    "daadirbakar",
    "dad",
    "daddy",
    "dark mode",
    "deactivate account",
    "dear sir",
    "deepak kumar",
    "delay message",
    "delay notification",
    "delete all chat",
    "delete call history",
    "delete datum",
    "delete mail",
    "delete multiple message",
    "delete spam",
    "delete tab",
    "delete whatsapp",
    "description",
    "deserve one star",
    "destroy app",
    "det",
    "dhaka",
    "dis",
    "disable app",
    "discrib",
    "dj",
    "do verification",
    "do completely unnecessary overhaul",
    "do effect",
    "do good",
    "do good work",
    "do great thing",
    "do group",
    "do other thing",
    "do same thing",
    "do so many thing",
    "do west",
    "dope app",
    "download gb",
    "download document",
    "download large file",
    "download new version",
    "download program",
    "download skype",
    "download speed problem",
    "download stuff",
    "download update",
    "download whatsapp",
    "downlode app",
    "drop sms",
    "dumbest app",
    "earn point",
    "earn crypto",
    "earn money",
    "easy access",
    "easy communication",
    "easy fun",
    "easy peasy",
    "easy to use",
    "edge",
    "edit review",
    "ee",
    "efficient app",
    "ek number",
    "email app",
    "enjoy brave",
    "enjoy call",
    "enjoy edge",
    "enjoy life",
    "enjoy moment",
    "enjoy privacy",
    "enjoyable app",
    "enter phone number",
    "enter program",
    "entertainment",
    "ew",
    "exalent",
    "excelent app",
    "excelente app",
    "excelente oportunidad",
    "excellen",
    "excellent ad blocker",
    "excellent choice",
    "excellent customer service",
    "excellent job",
    "excellent love",
    "excellent picture",
    "excellent product",
    "excellent services",
    "excellent tool",
    "exceptional browsing experience",
    "exceptional service",
    "excillent",
    "exellent app",
    "exillent",
    "exlant",
    "experience lot",
    "experience problem",
    "expert",
    "explore content",
    "extremely buggy",
    "fab",
    "face so many problem",
    "face technical problem",
    "fail",
    "fair",
    "fake app",
    "faltu app",
    "fan",
    "fantastic service",
    "fantastic work",
    "fast",
    "fast and active",
    "fast and secure browser",
    "fast download",
    "fast service",
    "fast way",
    "fav",
    "favorite messaging",
    "favorite web browser",
    "feature request",
    "find group",
    "find icon",
    "find line",
    "find lot",
    "find message",
    "find one",
    "find",
    "fire",
    "first choice",
    "first class",
    "first review",
    "first thing",
    "first time user",
    "fix message",
    "fix phone",
    "fix quality",
    "flawless",
    "follow step",
    "food",
    "format phone",
    "forward message",
    "free app",
    "free plastinee",
    "free service",
    "free text",
    "frequent crash",
    "fun app",
    "fun game",
    "fun time",
    "function",
    "fyi",
    "ga bisa login",
    "gak bisa",
    "get answer",
    "get ban",
    "get blank screen",
    "get block",
    "get call notification",
    "get cell service",
    "get d",
    "get error code",
    "get free call",
    "get hand",
    "get icon",
    "get issue",
    "get login code",
    "get messanger",
    "get new icon",
    "get new tablet",
    "get news",
    "get nitro",
    "get one",
    "get password",
    "get peace",
    "get phone call",
    "get phone number",
    "get picture",
    "get point",
    "get push notification",
    "get reward",
    "get service",
    "get sms",
    "get spam call",
    "get text message",
    "get this app",
    "get trouble",
    "get virus",
    "get well quality",
    "get wifi",
    "get work",
    "gf",
    "gg app",
    "gh",
    "ghatiya app",
    "ghh",
    "gi",
    "giod",
    "give star rating",
    "give star review",
    "give ad",
    "give bad experience",
    "give chance",
    "give choice",
    "give information",
    "give lot",
    "give message",
    "give money",
    "give negative star",
    "give negative score",
    "give nitro",
    "give opportunity",
    "give password",
    "give result",
    "give review",
    "give single star",
    "give time",
    "give trouble",
    "give try",
    "give two star",
    "give well rating",
    "give zero",
    "gj",
    "gm",
    "go hill",
    "goat",
    "god job",
    "gold",
    "goo",
    "good ad blocker",
    "good ad blocker browser",
    "good adblocker",
    "good and fast web browser",
    "good and most secure browser",
    "good and nice app",
    "good and secure app",
    "good and secure browser",
    "good and useful app",
    "good app chrome",
    "good app thank",
    "good appa",
    "good apppp",
    "good brower",
    "good call quality",
    "good carrier service",
    "good choice",
    "good clear picture",
    "good contact",
    "good dark mode",
    "good e",
    "good email client",
    "good evening",
    "good experiance",
    "good faster",
    "good feature",
    "good filter",
    "good functionality",
    "good google",
    "good hai",
    "good idea",
    "good improvement",
    "good information",
    "good internet",
    "good ish",
    "good l",
    "good life",
    "good love",
    "good luck app",
    "good massager",
    "good network",
    "good news",
    "good phone service",
    "good picture",
    "good private messenger",
    "good program",
    "good quality audio",
    "good quality call",
    "good quality video",
    "good quality video call",
    "good regard",
    "good response",
    "good right",
    "good security",
    "good signal",
    "good sound quality",
    "good soup",
    "good viber",
    "good voice",
    "good vpn",
    "goodgoodgood",
    "gooe",
    "gooodd",
    "gooog",
    "goooooood",
    "gooooooooood",
    "got free sim card",
    "goto",
    "gr",
    "gr app",
    "greaat",
    "great app thank",
    "great browser app",
    "great call quality",
    "great chat",
    "great clarity",
    "great fun",
    "great function",
    "great group",
    "great help",
    "great improvement",
    "great info",
    "great mail provider",
    "great messenger",
    "great phone app",
    "great phone service",
    "great private browser",
    "great problem",
    "great server",
    "great sound quality",
    "great system",
    "great texting",
    "great use",
    "great ux",
    "greet",
    "grt",
    "gugu",
    "gy",
    "hacker",
    "hafsat",
    "haha",
    "hahahahaha",
    "hang phone",
    "happy",
    "happy birthday tj",
    "hassle",
    "hate google",
    "hate new font",
    "have information",
    "have star",
    "have add",
    "have all friend",
    "have alot",
    "have background",
    "have bill",
    "have button",
    "have call",
    "have connection",
    "have connection issue",
    "have connection problem",
    "have conversation",
    "have delete option",
    "have different number",
    "have effect",
    "have enough credit",
    "have excellent experience",
    "have excellent service",
    "have extension",
    "have facility",
    "have few bug",
    "have firefox",
    "have galaxy s ultra",
    "have good connection",
    "have good feature",
    "have good luck",
    "have good quality",
    "have good signal",
    "have google",
    "have great day",
    "have great time",
    "have group",
    "have group chat",
    "have gv number",
    "have job",
    "have less ad",
    "have life",
    "have load",
    "have look",
    "have love",
    "have major problem",
    "have many bug",
    "have messenger",
    "have more feature",
    "have most option",
    "have multiple number",
    "have new email",
    "have nice feature",
    "have old tab",
    "have one issue",
    "have opportunity",
    "have plenty",
    "have really hard time",
    "have request",
    "have room",
    "have same phone number",
    "have second phone",
    "have second phone number",
    "have so many friend",
    "have subscription",
    "have tablet",
    "have too many ad",
    "have unstable connection",
    "have url bar",
    "have use",
    "have very good experience",
    "have way too many ad",
    "have whatsapp",
    "have yahoo",
    "have yahoo email",
    "hear call",
    "heavy app",
    "help full app",
    "help user",
    "helpful",
    "hi guy",
    "hide number",
    "highlight word",
    "highquality",
    "highs scores",
    "hio",
    "hj",
    "hope app",
    "hyeer",
    "hyy",
    "idiot app",
    "igg",
    "ilove app",
    "iluvit",
    "import contact",
    "improve alot",
    "improve business",
    "improve line voom",
    "improve quality",
    "improve speed",
    "increase font",
    "instal late update",
    "instal skype",
    "install ap",
    "install old version",
    "install one",
    "install update",
    "install whatsapp",
    "install whatsapp business",
    "interesting app",
    "internet",
    "invalid phone number",
    "invite friend",
    "irfan",
    "irritate app",
    "it",
    "itz",
    "j gorup",
    "jabardast",
    "jakir",
    "jass nijjar",
    "jay shree krishna",
    "je",
    "jhakass",
    "jhh",
    "join chat",
    "join group chat",
    "join groupchat",
    "join meeting",
    "join open chatroom",
    "join server",
    "joke",
    "joss",
    "just perfect",
    "just trash",
    "juu",
    "ka app hai",
    "kajal",
    "kaka",
    "kakao talk",
    "karthik",
    "keep force",
    "keep message",
    "keep sms support",
    "keep tab",
    "khin",
    "kick people",
    "kinda",
    "kiran",
    "know app",
    "know one",
    "know reason",
    "know thing",
    "know y",
    "kophyo",
    "lalajaanlalajaan",
    "lali",
    "late update attempt",
    "learn app",
    "learn lot",
    "learn thing",
    "leave account",
    "leave house",
    "less ad",
    "lifesaver",
    "light",
    "like aap",
    "like all filter",
    "like firefox",
    "like friend",
    "like google",
    "like kakao talk",
    "like layout",
    "like messenger kids",
    "like microsoft",
    "like new font",
    "like old one",
    "like phone",
    "like quality",
    "like save",
    "like snapchat",
    "like so much",
    "like telegram",
    "like this app",
    "like video",
    "like whatapp",
    "like whatsapp",
    "like yahoo",
    "likey",
    "limit account",
    "link",
    "lisabethdixon save",
    "ll",
    "load ad",
    "load new email",
    "lock app",
    "lock number",
    "log",
    "login error",
    "login i",
    "lol",
    "long time",
    "look number",
    "lose all chat",
    "lose all comcast email",
    "lose all open tab",
    "lose feature",
    "lose language",
    "lose old account",
    "lose service",
    "lose signal",
    "lousy app",
    "love ability",
    "love ad blocking",
    "love apk",
    "love application browser",
    "love brave browser",
    "love collection",
    "love convenience",
    "love dis",
    "love ease",
    "love encryption",
    "love end",
    "love freak app",
    "love functionality",
    "love google meet",
    "love idea",
    "love itttt",
    "love line app",
    "love love",
    "love love love",
    "love microsoft",
    "love new feature",
    "love note",
    "love opera browser",
    "love phone app",
    "love private tab",
    "love quality",
    "love search engine",
    "love simplicity",
    "love so much",
    "love video",
    "love vpn",
    "love whatsapp business",
    "love yahoo email",
    "love you guy",
    "lo",
    "mabagal",
    "mahaveer",
    "mahirap gamitin",
    "mail",
    "main number",
    "make communication",
    "make day",
    "make god",
    "make group",
    "make important call",
    "make korean friend",
    "make life",
    "make lot",
    "make mistake",
    "make new email",
    "make outgoing call",
    "make phone",
    "make phone lag",
    "make profile",
    "make purchase",
    "make sound",
    "make space",
    "make text",
    "make update",
    "make video",
    "make voice and video call",
    "make voise",
    "make work",
    "mal ware",
    "man",
    "manage app",
    "mantul",
    "many option",
    "mark msg",
    "marvelous app",
    "masha allah",
    "massage",
    "may",
    "md abirhassan",
    "me gusta mucho",
    "meet new people",
    "mess message",
    "message developer",
    "message people",
    "messager",
    "messanger",
    "messge",
    "microsoft",
    "miss message",
    "mo",
    "money",
    "monitor app",
    "mood",
    "moron",
    "most awful app",
    "most bad app",
    "most secure browser",
    "most useful app",
    "most useless app",
    "mostly good app",
    "move file",
    "movie download",
    "mozilla",
    "mr",
    "muy",
    "muy bueno",
    "mwaj hasani",
    "nade",
    "nadeemjohn",
    "naic",
    "naice app",
    "naise",
    "naiss app",
    "nandini",
    "navigate app",
    "nay",
    "need email",
    "need chrome extension support",
    "need contact",
    "need dark mode",
    "need fixing",
    "need integration",
    "need it",
    "need lock",
    "need material",
    "need privacy",
    "need qr code",
    "need skype",
    "need tab",
    "need upgrade",
    "need verification",
    "need wechat user",
    "neelam",
    "network problem",
    "new feature",
    "new ui suck",
    "new version",
    "news",
    "next level",
    "nic application",
    "nice and good app",
    "nice apo",
    "nice app google meet",
    "nice app love",
    "nice browser app",
    "nice carrier service",
    "nice communication app",
    "nice improvement",
    "nice interface",
    "nice opera",
    "nice opera mini",
    "nice place",
    "nice work app",
    "nicer",
    "nicey",
    "nicw",
    "nis",
    "nise",
    "nn",
    "nonsense",
    "nonsense app",
    "not good ap",
    "not problem",
    "not work",
    "obtain verification code",
    "odli",
    "ohk",
    "ok banget",
    "okie",
    "okokok",
    "oks",
    "one thing",
    "only browser",
    "only reason",
    "open",
    "open chrome",
    "open image",
    "open kakaotalk",
    "open messenger account",
    "open messenger app",
    "open pdf",
    "open profile",
    "open tab",
    "open video",
    "open web page",
    "open wechat app",
    "open whatsapp business",
    "open yahoo email",
    "open youtube",
    "opera browser",
    "oppp",
    "opppi",
    "opppp",
    "opppppp",
    "opt",
    "optional",
    "organize tab",
    "osam",
    "osome",
    "ossam",
    "ossam app",
    "osum",
    "outstanding app",
    "overall good privacy",
    "overall very good app",
    "pari",
    "paste link",
    "pay time",
    "pay",
    "perfect experience",
    "perfect way",
    "perfekt",
    "perform",
    "perform task",
    "pic",
    "picture",
    "pl",
    "place phone call",
    "play app",
    "play minecraft",
    "play service",
    "play video game",
    "play voice message",
    "play youtube video",
    "play",
    "please fix",
    "poor experience",
    "poor quality",
    "popup",
    "post message",
    "post review",
    "pradeep kumar",
    "prakash",
    "pramod",
    "prefer app",
    "prefer chrome",
    "prefer yahoo",
    "preferred browser",
    "press create account",
    "pretty good browser",
    "pretty great app",
    "pretty solid app",
    "protection",
    "pure garbage",
    "push notification",
    "put name",
    "put app",
    "put correct password",
    "put credit",
    "put emoji",
    "put ios discord",
    "put phone",
    "qqq",
    "quick browser",
    "qwertyuiop",
    "rajesh",
    "rajib",
    "rakesh",
    "reach friend",
    "reactivate account",
    "read mode",
    "read receipt",
    "read website",
    "real app",
    "really good experience",
    "really nice application",
    "really",
    "rearrange tab",
    "receive call screen",
    "receive e",
    "receive information",
    "receive messages",
    "receive new message",
    "receive photo",
    "receive problem",
    "receive video",
    "receive video call",
    "recieve message",
    "recive verification code",
    "recommend lot",
    "recommend",
    "record video",
    "reduce ad",
    "reduce number",
    "refresh page",
    "register new account",
    "register",
    "reinstall wechat",
    "release number",
    "release update",
    "reliable service",
    "remember password",
    "remove",
    "remove ai feature",
    "remove channel feature",
    "remove channel option",
    "remove chrome",
    "remove contact",
    "remove functionality",
    "remove option",
    "remove sm",
    "remove sms",
    "reopen app",
    "reopen app activity",
    "report problem",
    "request wechat company",
    "require facebook account",
    "require permission",
    "require text message",
    "reset",
    "restart app",
    "restore account",
    "restore backup",
    "restore chat",
    "restore chat history",
    "restore contact",
    "restore delete contact",
    "restore phone",
    "retrieve email",
    "retrieve previous contact",
    "rewrite review",
    "ridoy",
    "ring",
    "ritik",
    "rofiqhosen",
    "ruin phone",
    "ruin this damn app",
    "run javascript",
    "s app",
    "safety",
    "sahi hai",
    "saisai",
    "salamat",
    "samir",
    "sandar",
    "satisfaction",
    "save app",
    "save contact change",
    "save image",
    "save internet",
    "save life",
    "save message",
    "save phone number",
    "save problem",
    "save status",
    "saw",
    "sawman",
    "say account failure",
    "say ad",
    "say connection",
    "say server failure",
    "say unstable network",
    "saya setujuh dengan aplikasih ini",
    "scam people",
    "screen call",
    "screw google",
    "screw phone",
    "search google",
    "search option",
    "secure",
    "security",
    "see browser",
    "see call history",
    "see face",
    "see family",
    "see feature",
    "see info",
    "see information",
    "see kid",
    "see lot",
    "see option",
    "see phone number",
    "see son",
    "see status",
    "see sticker",
    "see story",
    "see use",
    "sei akta app",
    "select email",
    "select message",
    "select option",
    "sell number",
    "send activation code",
    "send ad",
    "send app",
    "send big file",
    "send call",
    "send cod",
    "send emoji",
    "send field",
    "send group",
    "send international number",
    "send invalid code",
    "send invite",
    "send massege",
    "send messag",
    "send otp",
    "send phone number",
    "send problem",
    "send same email",
    "send sim card",
    "send sms verification",
    "send sms verification code",
    "send spam",
    "send status",
    "send thing",
    "send verfication code",
    "send vid",
    "serve purpose",
    "server error",
    "set app",
    "set home page",
    "set homepage",
    "setup account",
    "sexy video",
    "sf",
    "share",
    "share app",
    "share information",
    "share link",
    "share message",
    "share status",
    "shi jun ang",
    "show company name",
    "show error message",
    "show medium",
    "show network error",
    "show nsfw",
    "show sender name",
    "show server error",
    "show wrong information",
    "shut",
    "sign error",
    "sign kid",
    "sign option",
    "simple app",
    "sira",
    "sk",
    "slow download",
    "slow speed",
    "slowest app",
    "smooth browsing",
    "snapchat",
    "so awesome",
    "so bad",
    "so bad experience",
    "so buggy",
    "so far complaint",
    "so far good",
    "so far good browser",
    "so good application",
    "so many ad",
    "so many error",
    "so many issue",
    "so much love",
    "so nice",
    "soboface aaaaaaaaaa",
    "sock",
    "soe",
    "sogood",
    "solid browser",
    "solve thank",
    "somalia",
    "something problem",
    "song",
    "soooooo good",
    "sooper",
    "spectacular",
    "speechless",
    "spend hour",
    "spend time",
    "splendid experience",
    "split screen",
    "steal information",
    "steal money",
    "stop service",
    "store contact",
    "struggle",
    "stupid verification",
    "suck datum",
    "suck man",
    "sujit",
    "suka",
    "sun",
    "super appa",
    "super ganda",
    "super service",
    "super useful app",
    "superb browser",
    "superb experience",
    "superb quality",
    "superb service",
    "supergirl star",
    "support addon",
    "support app",
    "support sms",
    "suprb",
    "surendra",
    "surf internet",
    "sweet app",
    "sweet",
    "swift",
    "switch phone",
    "sync datum",
    "take alot",
    "take app",
    "take call",
    "take control",
    "take more and more space",
    "take more than hour",
    "take photo",
    "take pic",
    "take place",
    "take screen shot",
    "take selfie",
    "take too long time",
    "take update",
    "tangina",
    "tap screen",
    "tell other",
    "tell people",
    "tell truth",
    "tell u",
    "text",
    "theme icon",
    "thik thak",
    "third party",
    "three year",
    "tidak bisa login",
    "time error",
    "timmy croft qb",
    "too many advert",
    "too many notification",
    "too many popup",
    "too many spam",
    "too much bug",
    "too much spam email",
    "top credit",
    "totally trash",
    "translate email",
    "transport",
    "truly good browser",
    "trust app",
    "trust browser",
    "trust signal",
    "try number",
    "try it",
    "try many method",
    "turn dark mode",
    "turn setting",
    "un",
    "unban account",
    "understand app",
    "understand need",
    "understand point",
    "uninstall",
    "uninstall whatsapp",
    "uninstalling",
    "unlock account",
    "unnecessary ad",
    "unstable network",
    "update time",
    "update discord",
    "update everytime",
    "update feature",
    "update information",
    "upload gifs",
    "use device",
    "use money",
    "use ad",
    "use alot",
    "use android",
    "use emoji",
    "use excellent sound quality",
    "use extension",
    "use ff",
    "use full app",
    "use hand",
    "use information",
    "use iphone",
    "use issue",
    "use microsoft browser",
    "use ms edge",
    "use one",
    "use one phone",
    "use other browser",
    "use pixel",
    "use qr code",
    "use samsung a",
    "use samsung fold",
    "use samsung internet",
    "use search engine",
    "use space",
    "use texting",
    "use too much datum",
    "use trash",
    "use update",
    "use watsapp",
    "use wifi",
    "use wonderful app",
    "use yahoo email",
    "useless bloatware",
    "user friendly",
    "user friendly app",
    "usingnit almost yr",
    "uwu",
    "v app",
    "v nice app",
    "value privacy",
    "vare",
    "ver cool",
    "verification",
    "verification code",
    "verification problem",
    "verify app",
    "verry nice app",
    "versatile app",
    "very app",
    "very buggy",
    "very cool",
    "very fine app",
    "very glitchy",
    "very good and fast app",
    "very good ap",
    "very good app love",
    "very good apps",
    "very good communication app",
    "very good job",
    "very good performance",
    "very good quality video call",
    "very good sarvice",
    "very good security",
    "very good software",
    "very good tool",
    "very good way",
    "very good whatsapp",
    "very goood",
    "very great browser",
    "very helpful great app",
    "very helpful",
    "very high quality",
    "very interesting app",
    "very nice and good app",
    "very nice and good experience",
    "very nice and useful application",
    "very nice software",
    "very nice work",
    "very super app",
    "very useful",
    "very useful aap",
    "very usefull app",
    "very very nice",
    "very wonderful app",
    "vibersafechatsa",
    "video chat",
    "view chat",
    "view status",
    "view video",
    "vikas",
    "violation",
    "vip app",
    "wa",
    "wah",
    "waiste time",
    "want ad",
    "want dark mode",
    "want info",
    "want information",
    "want number",
    "want phone",
    "want rating",
    "want signal",
    "want",
    "waooo",
    "watch porn",
    "watch stream",
    "watch version",
    "wawa",
    "welcome",
    "well good",
    "well privacy",
    "well quality",
    "well service",
    "well then chrome",
    "west app",
    "wifi",
    "win prize",
    "wiz",
    "wonderful application",
    "wonderful way",
    "wonderfull app",
    "wooooow",
    "work google",
    "work junk",
    "world",
    "worth",
    "wow app",
    "wow good app",
    "write mail",
    "write number",
    "xi",
    "xl",
    "yahoo app",
    "yahoo mail",
    "yahoo work",
    "yc",
    "yessir",
    "yey",
    "yoge",
    "yos",
    "you option"
]
}'